version: '3.4'

services:
  swagger-ui-consolidated:
    image: swagger-ui-consolidated
    container_name: swagger-ui-consolidated
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/docker-entrypoint.d/app_config.sh:/docker-entrypoint.d/app_config.sh:ro
    environment:
      APP_CONFIG: ${APP_CONFIG}

